// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ysbhpstyzuhiezfzzpjx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlzYmhwc3R5enVoaWV6Znp6cGp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4NDA3MDAsImV4cCI6MjA2NzQxNjcwMH0.lhRvKM0q44mASwkTL0n9GAPHLLp-S5U3EVVL8lPWWjU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});